#!/bin/bash

 if [ -n "$1" ]; then
        var="$1"
    else
        echo
        echo "Usage: copy_keys.sh <host name>"
        echo 
        echo "Example - copy_keys.sh wwwoma01prd"
        exit
    fi

ssh-copy-id -i ~/.ssh/id_rsa.pub $1