#!/bin/bash

 if [ -n "$1" ]; then
        filesystem="$1"
    else
        echo
        echo "Usage: monitor_realtime_disk_space.sh <filesystem>"
        echo 
        echo "Example - monitor_realtime_disk_space.sh var"
        exit
    fi

echo "Filesystem    Avail      %" 
x=1
while [ $x = 1 ]; do
    df -h | grep $filesystem | awk '{print $5 "         " $3 "      " $4}'
    sleep 15
done
