#!/bin/bash

echo "Enter the file_type of files you want to read (i.e. music, video, etc)"
read file_typ
	
echo "Enter the fulluy qualified (not relitive) path containing the files (i.e. /Users/jpwalker/Music "
read source_path

echo "Making file list..."
		#find $source_path | sed s/[[:punct:]]/\ /g | sed s/[0-9]*//g | grep -v Artwork | sort | gzip -9 -f > /Volumes/11/"$file_type"_files.txt.gz
find "$source_path" | sed s/[[:punct:]]/\ /g | sed s/[0-9]*//g | grep -v Artwork | sort | gzip -9 -f > ~/tmp/"$file_type".txt.gz
echo "Done"