#!/bin/bash

path=$1
cd $path
files=`ls`

for i in $files;do
    name=`echo $i` 
    check_ascii=`echo "$name" | grep %`
    if [ -n "$check_ascii" ]; then
        new_name=`echo $name | sed s/\%/\_/g`
        mv -v $i "$new_name"
    fi

        files2=`ls`
        for i in $files2;do
            name=`echo $i` 
            check_ascii=`echo "$name" | grep 20`
            if [ -n "$check_ascii" ]; then
                new_name=`echo $name | sed s/\20/\/g`
                mv -v $i "$new_name"
            fi
        done

done