#!/bin/bash

DATE=`date +%m-%d-%y`

/usr/bin/rsync -avP goto mgtoma05prd:~/ | tee -a ~/logs/rsync.log.$DATE
/usr/bin/rsync -avP .goto mgtoma05prd:~/ | tee -a ~/logs/rsync.log.$DATE
/usr/bin/rsync -avP scripts/ mgtoma05prd:~/scripts/ | tee -a ~/logs/rsync.log.$DATE

