#!/bin/bash

if [ -n "$1" ]; then
        var="$1"
    else
        echo
        echo "Usage: dos2mac <file name>"
        echo 
        echo "Example - dos2mac myfile"
        exit
    fi

echo "Converting $var..."
mv $var $var.tmp
cat $var.tmp | col -b > $var
/bin/rm $var.tmp
echo "Done!"