#!/bin/bash

if [ -n "$1" ]; then
        var="$1"
    else
        echo
        echo "Usage: dsaconv.sh <source directory"
        echo 
        echo "Example - dsaconv.sh /home/DSA"
        exit
    fi

source_dir=$1
dsa_files=`ls $source_dir/*.gz`


for i in $dsa_files;do
    #<DEBUG>
    #echo "sudo /home/jpwalker/DSA/ibm_utl_dsa_dsytd3h-9.51_portable_rhel6_x86-64.bin -v -i $i"
    #<DEBUG>
    sudo /home/jpwalker/DSA/ibm_utl_dsa_dsytd3h-9.51_portable_rhel6_x86-64.bin -x -b -v -i $i
done

sudo mkdir $source_dir/done
sudo chmod 777 $source_dir/done
sudo rsync -avP /var/log/IBM_Support/ $source_dir/done/
sudo rm -rf /var/log/IBM_Support/*