#!/usr/bin/bash

if [ -n "$1" ]; then
        var="$1"
    else
        echo
        echo "Usage: tasks.sh <program name>"
        echo 
        echo "Example - tasks.sh chrome"
        exit
    fi

taskname=$1
task=$taskname.exe

tasklist /FI "imagename eq $task"
